apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homelab-api-secrets
  namespace: homelab-api
spec:
  encryptedData:
    grafana-token: AgBKFAAA2T2ryYiKmeey3nfkh6oXGzQyDJbbY1itCFY0qEhglV4f57VHcId9pc0ZMs5bqH9YMpsyz98WxAX3vggpre7Ludxx2eRfrCWyeqvw7csuRbN/Twvv3av/PIIHH/LP8/V1Wc3q+UdRezO8ugWYL5Evy8rthWWUjPyHknfNpgwNmpHU2I5lpOUDOmXOhYH7y9X9slUZXwOA8tt3rtE/nb3XU+giYJQEB8ZFSgcA0Umcon2ttSfvJYPZ1uWoooiHpHE6sNIzcPjCIoymZ9oiafOiVn5yuzeBzQp83NZTmUyIW7sCertu/IuiEjj9uKQZQDdomCOKpYyfhofXn324RB/N+ozSv3rc769qqP1ev7+i6J6XToonLKelzNti90rn1AuR4dk+TKf4DbeyBdmNKUHuhh4boSinfgMmfgyLFq/RroIRn6vs9RQ/9TiLrPzhoJBDeN9RcTy93/uaS7Qqc3udGIzeuXQnSNCKV1XE6Jyadd+VRSMrfhgBHL1/t6g0Tl0tm8tPjfy6AK+JqS0Dm5OjvO0pCC3YmpRkF/PX453ewb3i7w6nNfLXft2CBrz7lxV91atCc+U5Iqlvh6AKRkk0vc0Bf7IxxjTIRc4S1SUwajjgoVDtl68mWS777LCStPcQTxOsJaegc7lSL8orTygOX7BNfFKIR6RqzFx1ZMf9SNxzppkai/wqA2GrRiVqra3EBYoHGU9v2GBMGHmBeOjdZi3ajEfzBhJNcEEq9V2VyuL9AUtki9T2JpOR
  template:
    metadata:
      name: homelab-api-secrets
      namespace: homelab-api
